import type { WorkItem, WorkType } from "@schoolquest/domain";
import { toEpochMinutes } from "@schoolquest/domain";

/**
 * Breaking a project into stages that can actually be started.
 *
 * "Research Paper — 4 hours" is not a task, it is a subject heading. Nobody sits down and
 * does a research paper; they pick a topic, then find sources, then outline. For a student
 * whose central difficulty is *starting*, the gap between those two framings is the whole
 * problem — and it is why a term paper can sit untouched for six weeks while smaller work
 * gets done every day. The small work has a visible first move.
 *
 * So this turns one blob into an ordered set of stages, each with its own share of the
 * effort and its own internal deadline working back from the real one.
 *
 * Deliberately templated, not generated by a model. Three reasons, in order of weight:
 * the stages of a paper are not a mystery that needs intelligence; a deterministic function
 * can be tested, explained, and re-run identically; and the coach is forbidden from doing
 * the coursework, so having it invent the structure of an essay would sit uncomfortably
 * close to that line. The templates are a starting point the student edits, never a
 * prescription.
 */

export interface StageTemplate {
  title: string;
  /** Share of the project's effort, summing to 1 across a template. */
  share: number;
  /**
   * Share of the runway this stage should be finished by, so stages get real internal
   * deadlines instead of all landing on the due date.
   */
  dueAtFraction: number;
  cognitiveDemand: "low" | "medium" | "high";
}

/**
 * Stage sets by work type.
 *
 * The front-loading is intentional and is the part that matters: every template gives the
 * first stage a small share and an early deadline, because the point is to make starting
 * cheap. A first stage worth 10% of a paper and due a fifth of the way in is a thing a
 * student can do on a bad day.
 */
const TEMPLATES: Partial<Record<WorkType, StageTemplate[]>> = {
  paper: [
    { title: "Settle the topic and re-read the prompt", share: 0.1, dueAtFraction: 0.15, cognitiveDemand: "low" },
    { title: "Gather and skim sources", share: 0.2, dueAtFraction: 0.4, cognitiveDemand: "medium" },
    { title: "Outline the argument", share: 0.15, dueAtFraction: 0.55, cognitiveDemand: "high" },
    { title: "Write the draft", share: 0.35, dueAtFraction: 0.85, cognitiveDemand: "high" },
    { title: "Revise, check citations, submit", share: 0.2, dueAtFraction: 1, cognitiveDemand: "medium" },
  ],
  presentation: [
    { title: "Settle the angle and the takeaway", share: 0.15, dueAtFraction: 0.2, cognitiveDemand: "medium" },
    { title: "Gather the material", share: 0.25, dueAtFraction: 0.5, cognitiveDemand: "medium" },
    { title: "Build the slides", share: 0.3, dueAtFraction: 0.8, cognitiveDemand: "medium" },
    { title: "Rehearse out loud, twice", share: 0.3, dueAtFraction: 1, cognitiveDemand: "low" },
  ],
  group_project: [
    { title: "Agree who is doing what, in writing", share: 0.1, dueAtFraction: 0.15, cognitiveDemand: "low" },
    { title: "Do your part's research", share: 0.25, dueAtFraction: 0.45, cognitiveDemand: "medium" },
    { title: "Build your part", share: 0.35, dueAtFraction: 0.75, cognitiveDemand: "high" },
    { title: "Combine and reconcile with the group", share: 0.2, dueAtFraction: 0.92, cognitiveDemand: "medium" },
    { title: "Final pass and submit", share: 0.1, dueAtFraction: 1, cognitiveDemand: "low" },
  ],
  lab: [
    { title: "Read the procedure before the session", share: 0.15, dueAtFraction: 0.25, cognitiveDemand: "low" },
    { title: "Work up the data", share: 0.4, dueAtFraction: 0.7, cognitiveDemand: "high" },
    { title: "Write up and submit", share: 0.45, dueAtFraction: 1, cognitiveDemand: "medium" },
  ],
  exam_prep: [
    { title: "Map what is on it and what you already know", share: 0.15, dueAtFraction: 0.2, cognitiveDemand: "low" },
    { title: "First pass over the weak areas", share: 0.3, dueAtFraction: 0.5, cognitiveDemand: "high" },
    { title: "Practise from memory, not from notes", share: 0.35, dueAtFraction: 0.8, cognitiveDemand: "high" },
    { title: "Final review of what still will not stick", share: 0.2, dueAtFraction: 1, cognitiveDemand: "medium" },
  ],
  problem_set: [
    { title: "Read every question first", share: 0.1, dueAtFraction: 0.2, cognitiveDemand: "low" },
    { title: "Work the ones you can do", share: 0.45, dueAtFraction: 0.6, cognitiveDemand: "medium" },
    { title: "Attack the ones you cannot, and note what to ask", share: 0.35, dueAtFraction: 0.9, cognitiveDemand: "high" },
    { title: "Check and submit", share: 0.1, dueAtFraction: 1, cognitiveDemand: "low" },
  ],
};

/** Anything without a template of its own gets a shape that fits almost any large task. */
const GENERIC: StageTemplate[] = [
  { title: "Look at it and work out what it involves", share: 0.15, dueAtFraction: 0.2, cognitiveDemand: "low" },
  { title: "Do the main body of the work", share: 0.55, dueAtFraction: 0.75, cognitiveDemand: "high" },
  { title: "Finish, check, and hand in", share: 0.3, dueAtFraction: 1, cognitiveDemand: "medium" },
];

/** Below this, stages are overhead rather than help — the thing is already one sitting. */
export const DECOMPOSABLE_MINUTES = 120;

/** Never propose a stage shorter than this; a 10-minute fragment is not a session. */
const MIN_STAGE_MINUTES = 15;

export interface ProposedStage {
  title: string;
  estimatedMinutes: number;
  /** Internal deadline, or null when the project itself has no known due date. */
  dueAt: string | null;
  cognitiveDemand: "low" | "medium" | "high";
  order: number;
}

export function canDecompose(item: WorkItem, effortMinutes: number): boolean {
  if (item.status === "completed" || item.status === "submitted" || item.status === "canceled") {
    return false;
  }
  return effortMinutes >= DECOMPOSABLE_MINUTES;
}

/**
 * Proposes stages for a project. Nothing is written anywhere — the caller shows these to
 * the student, who edits or rejects them before any of it becomes real. That review step is
 * the same discipline the syllabus extraction follows: the app can suggest, but the student
 * confirms.
 *
 * `availableFrom` is where the runway starts. It should be now, not the project's creation
 * date, or a project picked up late gets stages whose internal deadlines are already past.
 */
export function proposeStages(
  item: WorkItem,
  effortMinutes: number,
  availableFrom: string,
): ProposedStage[] {
  const template = TEMPLATES[item.workType] ?? GENERIC;

  // Round each stage, then give the remainder to the largest one, so the parts always sum
  // to the whole. Silently losing four minutes to rounding would make the stage list
  // disagree with the project total it came from.
  const raw = template.map((stage) =>
    Math.max(MIN_STAGE_MINUTES, Math.round(effortMinutes * stage.share)),
  );
  const drift = effortMinutes - raw.reduce((sum, m) => sum + m, 0);
  const largest = raw.indexOf(Math.max(...raw));
  raw[largest] = Math.max(MIN_STAGE_MINUTES, raw[largest]! + drift);

  const start = toEpochMinutes(availableFrom);
  const due = item.dueAt ? toEpochMinutes(item.dueAt) : null;
  const runway = due === null ? null : Math.max(0, due - start);

  return template.map((stage, index) => ({
    title: stage.title,
    estimatedMinutes: raw[index]!,
    dueAt:
      runway === null
        ? null
        : new Date((start + runway * stage.dueAtFraction) * 60_000).toISOString(),
    cognitiveDemand: stage.cognitiveDemand,
    order: index,
  }));
}
