#!/usr/bin/env node
/**
 * Everything a fresh clone needs before `pnpm dev` will work, done once.
 *
 * Written because the gap between "cloned the repo" and "the app opens" was four undocumented
 * steps, two of which fail silently: `.dev.vars` is gitignored so a fresh clone has none, and a
 * Worker with no `AUTH_SECRET` starts happily and then throws on the first sign-in. The local D1
 * has no tables until migrations run, which surfaces as `no such table: users` from inside a
 * fetch handler — a stack trace, not an instruction.
 *
 * Idempotent on purpose: running it twice must be safe, because the first thing anyone does when
 * something looks wrong is run the setup command again. It never overwrites an existing
 * `.dev.vars`, because that file may hold a real key.
 *
 *   node tools/setup.mjs        (or: pnpm run setup -- `pnpm setup` alone is pnpm's own command)
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { randomBytes } from "node:crypto";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const API = join(ROOT, "apps", "api");
const DEV_VARS = join(API, ".dev.vars");

const ok = (m) => console.log(`  ok    ${m}`);
const did = (m) => console.log(`  done  ${m}`);
const warn = (m) => console.log(`  note  ${m}`);

console.log("\nSchoolQuest local setup\n");

// --- 1. Secrets file.
if (existsSync(DEV_VARS)) {
  const text = readFileSync(DEV_VARS, "utf8");
  ok(".dev.vars exists (left alone — it may hold a real key)");
  if (!/^AUTH_SECRET=.{16,}/m.test(text)) {
    warn("AUTH_SECRET looks missing or too short; sign-in will fail until it is set");
  }
} else {
  /**
   * A real random secret rather than a placeholder.
   *
   * It signs session tokens and derives the key that encrypts a student's OpenRouter key, so a
   * shared example value would mean every install could decrypt every other install's
   * credentials. Generating one here costs nothing and removes the step people skip.
   */
  writeFileSync(
    DEV_VARS,
    [
      "# Generated by tools/setup.mjs. Not committed — this file is gitignored.",
      "#",
      "# AUTH_SECRET signs sign-in sessions and encrypts stored OpenRouter keys. Changing it logs",
      "# everyone out and makes any stored key unreadable (the app treats that as 'no key set').",
      `AUTH_SECRET=${randomBytes(32).toString("hex")}`,
      "",
      "# Optional. Leave it out and each person adds their own key in Setup → AI and model,",
      "# which is the arrangement this app is built around.",
      "# OPENROUTER_API_KEY=sk-or-v1-...",
      "",
      "# Optional. With no mail provider the sign-in link comes back in the response instead of",
      "# by email, which is what makes a local run possible with no email set up at all.",
      "# RESEND_API_KEY=re_...",
      "",
    ].join("\n"),
  );
  did("wrote apps/api/.dev.vars with a fresh AUTH_SECRET");
}

// --- 2. Local database.
try {
  execFileSync("pnpm", ["--filter", "@schoolquest/api", "db:migrate:local"], {
    cwd: ROOT,
    stdio: "pipe",
    shell: process.platform === "win32",
  });
  did("applied database migrations to the local D1");
} catch (e) {
  console.log(`  FAIL  migrations did not apply:\n${String(e.stdout ?? e.message).slice(-600)}`);
  process.exitCode = 1;
}

console.log("\nNext: pnpm dev, then open http://127.0.0.1:5173\n");
