/**
 * Emits seed/seed.sql from the reference semester in @schoolquest/fixtures.
 *
 * Generating the SQL from the same fixture the tests use means the demo account and the
 * regression suite can never drift apart.
 *
 * Run with:  npx tsx scripts/generate-seed.ts
 */
import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { buildSeedSemester } from "@schoolquest/fixtures";

const SEED_USER_ID = "usr_seed";
const SEED_EMAIL = "demo@schoolquest.local";

function sql(value: string | number | boolean | null): string {
  if (value === null) return "NULL";
  if (typeof value === "boolean") return value ? "1" : "0";
  if (typeof value === "number") return String(value);
  return `'${value.replace(/'/g, "''")}'`;
}

function insert(table: string, rows: Record<string, string | number | boolean | null>[]): string {
  if (rows.length === 0) return "";
  const columns = Object.keys(rows[0]!);
  const values = rows
    .map((row) => `  (${columns.map((c) => sql(row[c] ?? null)).join(", ")})`)
    .join(",\n");
  return `INSERT INTO ${table} (${columns.join(", ")}) VALUES\n${values};\n`;
}

const seed = buildSeedSemester(SEED_USER_ID);
const now = new Date().toISOString();

/**
 * The fixture is pinned to a fixed week so tests stay deterministic. A demo account
 * pinned to that same week would be useless outside it, so every date is shifted by whole
 * weeks to land on the current one. Shifting by a multiple of 7 days preserves the
 * weekday pattern the scenario depends on — the Tuesday library window stays on Tuesday.
 */
const SEED_ANCHOR = "2026-09-07"; // The fixture's Monday.
const DAY_MS = 24 * 60 * 60 * 1000;

function mondayOfThisWeek(): Date {
  const today = new Date();
  const utcMidnight = Date.UTC(today.getUTCFullYear(), today.getUTCMonth(), today.getUTCDate());
  const dayOfWeek = new Date(utcMidnight).getUTCDay();
  // getUTCDay is 0 for Sunday; step back to Monday.
  const offsetToMonday = (dayOfWeek + 6) % 7;
  return new Date(utcMidnight - offsetToMonday * DAY_MS);
}

const shiftWeeks = Math.round(
  (mondayOfThisWeek().getTime() - Date.parse(`${SEED_ANCHOR}T00:00:00Z`)) / (7 * DAY_MS),
);
const shiftMs = shiftWeeks * 7 * DAY_MS;

/** Shifts an ISO date or datetime by whole weeks, preserving the time component. */
function shift<T extends string | null>(value: T): T {
  if (value === null) return value;
  const shifted = new Date(Date.parse(value) + shiftMs).toISOString();
  return (value.length === 10 ? shifted.slice(0, 10) : shifted) as T;
}

/**
 * A DELETE that reaches the seed user's rows in a given table, walking whatever chain of
 * foreign keys connects it back to `users`.
 */
function deleteForSeed(table: string): string {
  const viaCourse = new Set([
    "grading_categories",
    "meeting_patterns",
    "source_documents",
    "work_items",
  ]);
  const viaTerm = new Set(["courses", "availability_rules", "commitments", "plan_versions"]);
  const viaWorkItem = new Set(["grade_results", "work_sessions", "dependencies"]);

  const termScope = `SELECT id FROM terms WHERE user_id = '${SEED_USER_ID}'`;
  const courseScope = `SELECT id FROM courses WHERE term_id IN (${termScope})`;
  const workItemScope = `SELECT id FROM work_items WHERE course_id IN (${courseScope})`;

  if (viaTerm.has(table)) return `DELETE FROM ${table} WHERE term_id IN (${termScope});`;
  if (viaCourse.has(table)) return `DELETE FROM ${table} WHERE course_id IN (${courseScope});`;
  if (viaWorkItem.has(table)) {
    const column =
      table === "dependencies" ? "successor_work_item_id" : "work_item_id";
    return `DELETE FROM ${table} WHERE ${column} IN (${workItemScope});`;
  }
  return `DELETE FROM ${table} WHERE user_id = '${SEED_USER_ID}';`;
}

const statements: string[] = [
  "-- Generated by scripts/generate-seed.ts. Do not edit by hand.",
  "-- Reference semester from docs/08-coding-agent-handoff.md section 10.",
  "",
  // Explicit deletes in dependency order. Relying on ON DELETE CASCADE is not safe here:
  // D1 does not guarantee foreign-key enforcement is on, and a half-cleared seed would
  // collide on primary keys the next time this runs.
  ...[
    "grade_results",
    "work_sessions",
    "dependencies",
    "work_items",
    "grading_categories",
    "meeting_patterns",
    "source_documents",
    "courses",
    "availability_rules",
    "commitments",
    "plan_versions",
    "coach_messages",
    "auth_sessions",
  ].map(deleteForSeed),
  "DELETE FROM terms WHERE user_id = 'usr_seed';",
  "DELETE FROM users WHERE id = 'usr_seed';",
  "",
  insert("users", [
    {
      id: SEED_USER_ID,
      email: SEED_EMAIL,
      display_name: "Demo Student",
      timezone: "America/New_York",
      theme: "plain",
      reduced_motion: false,
      detail_mode: "standard",
      created_at: now,
    },
  ]),
  insert("terms", [
    {
      id: seed.term.id,
      user_id: SEED_USER_ID,
      name: seed.term.name,
      start_date: shift(seed.term.startDate),
      end_date: shift(seed.term.endDate),
      status: seed.term.status,
      planning_preferences_json: JSON.stringify(seed.term.planningPreferences),
    },
  ]),
  insert(
    "courses",
    seed.courses.map((c) => ({
      id: c.id,
      term_id: c.termId,
      name: c.name,
      code: c.code,
      instructor: c.instructor,
      credits: c.credits,
      color_token: c.colorToken,
      expected_weekly_minutes: c.expectedWeeklyMinutes,
      target_grade: c.targetGrade,
      grading_confidence: c.gradingConfidence,
    })),
  ),
  insert(
    "grading_categories",
    seed.gradingCategories.map((g) => ({
      id: g.id,
      course_id: g.courseId,
      name: g.name,
      weight_percent: g.weightPercent,
      drop_rule_json: g.dropRule ? JSON.stringify(g.dropRule) : null,
      confidence_status: g.confidenceStatus,
    })),
  ),
  insert(
    "meeting_patterns",
    seed.meetingPatterns.map((m) => ({
      id: m.id,
      course_id: m.courseId,
      days_of_week: m.daysOfWeek.join(","),
      start_time: m.startTime,
      end_time: m.endTime,
      location: m.location,
      effective_start: shift(m.effectiveStart),
      effective_end: shift(m.effectiveEnd),
    })),
  ),
  insert(
    "commitments",
    seed.commitments.map((c) => ({
      id: c.id,
      term_id: c.termId,
      title: c.title,
      commitment_type: c.commitmentType,
      days_of_week: c.daysOfWeek.join(","),
      start_time: c.startTime,
      end_time: c.endTime,
      specific_date: shift(c.specificDate),
      flexibility: c.flexibility,
      locked: c.locked,
    })),
  ),
  insert(
    "availability_rules",
    seed.availabilityRules.map((a) => ({
      id: a.id,
      term_id: a.termId,
      day_of_week: a.dayOfWeek,
      start_time: a.startTime,
      end_time: a.endTime,
      energy_level: a.energyLevel,
      location: a.location,
      hardness: a.hardness,
    })),
  ),
  insert(
    "work_items",
    seed.workItems.map((w) => ({
      id: w.id,
      course_id: w.courseId,
      parent_work_item_id: w.parentWorkItemId,
      title: w.title,
      description: w.description,
      work_type: w.workType,
      available_at: shift(w.availableAt),
      due_at: shift(w.dueAt),
      points_possible: w.pointsPossible,
      grading_category_id: w.gradingCategoryId,
      category_share_percent: w.categorySharePercent,
      estimated_minutes: w.estimatedMinutes,
      remaining_minutes: w.remainingMinutes,
      cognitive_demand: w.cognitiveDemand,
      divisibility: w.divisibility,
      location_requirement: w.locationRequirement,
      status: w.status,
      source_confidence: w.sourceConfidence,
      user_priority: w.userPriority,
    })),
  ),
  insert(
    "dependencies",
    seed.dependencies.map((d) => ({
      id: d.id,
      predecessor_work_item_id: d.predecessorWorkItemId,
      successor_work_item_id: d.successorWorkItemId,
      dependency_type: d.dependencyType,
    })),
  ),
  insert(
    "grade_results",
    seed.grades.map((g) => ({
      id: g.id,
      work_item_id: g.workItemId,
      points_earned: g.pointsEarned,
      points_possible: g.pointsPossible,
      letter_grade: g.letterGrade,
      posted_at: shift(g.postedAt),
      confirmation_status: g.confirmationStatus,
      source_document_id: g.sourceDocumentId,
      dropped: g.dropped,
    })),
  ),
];

const outPath = join(dirname(fileURLToPath(import.meta.url)), "..", "seed", "seed.sql");
mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, statements.filter(Boolean).join("\n"));
console.log(`Wrote ${outPath}`);
