-- Generated by scripts/generate-seed.ts. Do not edit by hand.
-- Reference semester from docs/08-coding-agent-handoff.md section 10.
DELETE FROM grade_results WHERE work_item_id IN (SELECT id FROM work_items WHERE course_id IN (SELECT id FROM courses WHERE term_id IN (SELECT id FROM terms WHERE user_id = 'usr_seed')));
DELETE FROM work_sessions WHERE work_item_id IN (SELECT id FROM work_items WHERE course_id IN (SELECT id FROM courses WHERE term_id IN (SELECT id FROM terms WHERE user_id = 'usr_seed')));
DELETE FROM dependencies WHERE successor_work_item_id IN (SELECT id FROM work_items WHERE course_id IN (SELECT id FROM courses WHERE term_id IN (SELECT id FROM terms WHERE user_id = 'usr_seed')));
DELETE FROM work_items WHERE course_id IN (SELECT id FROM courses WHERE term_id IN (SELECT id FROM terms WHERE user_id = 'usr_seed'));
DELETE FROM grading_categories WHERE course_id IN (SELECT id FROM courses WHERE term_id IN (SELECT id FROM terms WHERE user_id = 'usr_seed'));
DELETE FROM meeting_patterns WHERE course_id IN (SELECT id FROM courses WHERE term_id IN (SELECT id FROM terms WHERE user_id = 'usr_seed'));
DELETE FROM source_documents WHERE course_id IN (SELECT id FROM courses WHERE term_id IN (SELECT id FROM terms WHERE user_id = 'usr_seed'));
DELETE FROM courses WHERE term_id IN (SELECT id FROM terms WHERE user_id = 'usr_seed');
DELETE FROM availability_rules WHERE term_id IN (SELECT id FROM terms WHERE user_id = 'usr_seed');
DELETE FROM commitments WHERE term_id IN (SELECT id FROM terms WHERE user_id = 'usr_seed');
DELETE FROM plan_versions WHERE term_id IN (SELECT id FROM terms WHERE user_id = 'usr_seed');
DELETE FROM coach_messages WHERE user_id = 'usr_seed';
DELETE FROM auth_sessions WHERE user_id = 'usr_seed';
DELETE FROM terms WHERE user_id = 'usr_seed';
DELETE FROM users WHERE id = 'usr_seed';
INSERT INTO users (id, email, display_name, timezone, theme, reduced_motion, detail_mode, created_at) VALUES
  ('usr_seed', 'demo@schoolquest.local', 'Demo Student', 'America/New_York', 'plain', 0, 'standard', '2026-07-27T19:43:49.456Z');

INSERT INTO terms (id, user_id, name, start_date, end_date, status, planning_preferences_json) VALUES
  ('trm_fall', 'usr_seed', 'Fall 2026', '2026-07-20', '2026-11-06', 'active', '{"maxDailyAcademicMinutes":240,"preferredSessionMinutes":45,"minSessionMinutes":20,"maxSessionMinutes":90,"breakMinutes":10,"protectedDaysOfWeek":[],"deadlineBufferDays":1}');

INSERT INTO courses (id, term_id, name, code, instructor, credits, color_token, expected_weekly_minutes, target_grade, grading_confidence) VALUES
  ('crs_psych', 'trm_fall', 'Developmental Psychology', 'PSY 210', 'Dr. Alvarez', 3, 'violet', 360, 90, 'confirmed'),
  ('crs_edu', 'trm_fall', 'Foundations of Childhood Education', 'EDU 240', 'Prof. Nakamura', 3, 'emerald', 300, 90, 'confirmed');

INSERT INTO grading_categories (id, course_id, name, weight_percent, drop_rule_json, confidence_status) VALUES
  ('gcat_psych_major', 'crs_psych', 'Major Projects', 40, NULL, 'confirmed'),
  ('gcat_psych_quiz', 'crs_psych', 'Quizzes', 30, '{"dropLowest":1}', 'confirmed'),
  ('gcat_psych_reading', 'crs_psych', 'Reading Responses', 30, NULL, 'confirmed'),
  ('gcat_edu_major', 'crs_edu', 'Major Projects', 35, NULL, 'confirmed'),
  ('gcat_edu_quiz', 'crs_edu', 'Quizzes', 25, '{"dropLowest":1}', 'confirmed'),
  ('gcat_edu_reading', 'crs_edu', 'Readings', 40, NULL, 'confirmed');

INSERT INTO meeting_patterns (id, course_id, days_of_week, start_time, end_time, location, effective_start, effective_end) VALUES
  ('mtg_psych', 'crs_psych', '1,3', '10:00', '11:15', 'Harmon Hall 204', '2026-07-20', '2026-11-06'),
  ('mtg_edu', 'crs_edu', '2,4', '09:00', '10:15', 'Education Building 110', '2026-07-20', '2026-11-06');

INSERT INTO commitments (id, term_id, title, commitment_type, days_of_week, start_time, end_time, specific_date, flexibility, locked) VALUES
  ('cmt_shift_tue', 'trm_fall', 'Work shift', 'work', '2', '17:00', '22:00', NULL, 'fixed', 1),
  ('cmt_shift_fri', 'trm_fall', 'Work shift', 'work', '5', '17:00', '22:00', NULL, 'fixed', 1),
  ('cmt_meals', 'trm_fall', 'Dinner', 'meal', '0,1,2,3,4,5,6', '18:00', '18:45', NULL, 'flexible', 0);

INSERT INTO availability_rules (id, term_id, day_of_week, start_time, end_time, energy_level, location, hardness) VALUES
  ('avl_mon_pm', 'trm_fall', 1, '13:00', '17:00', 'medium', 'anywhere', 'soft'),
  ('avl_tue_library', 'trm_fall', 2, '13:00', '14:30', 'high', 'library', 'soft'),
  ('avl_tue_pm', 'trm_fall', 2, '14:30', '16:30', 'medium', 'anywhere', 'soft'),
  ('avl_wed_pm', 'trm_fall', 3, '13:00', '17:00', 'high', 'anywhere', 'soft'),
  ('avl_thu_pm', 'trm_fall', 4, '11:00', '16:00', 'medium', 'anywhere', 'soft'),
  ('avl_fri_am', 'trm_fall', 5, '10:00', '15:00', 'low', 'anywhere', 'soft'),
  ('avl_sat', 'trm_fall', 6, '10:00', '15:00', 'medium', 'anywhere', 'soft'),
  ('avl_sun', 'trm_fall', 0, '12:00', '18:00', 'high', 'anywhere', 'soft');

INSERT INTO work_items (id, course_id, parent_work_item_id, title, description, work_type, available_at, due_at, points_possible, grading_category_id, category_share_percent, estimated_minutes, remaining_minutes, cognitive_demand, divisibility, location_requirement, status, source_confidence, user_priority) VALUES
  ('wi_psych_paper', 'crs_psych', NULL, 'Developmental Analysis Paper', '8-10 page analysis of a developmental case, APA format.', 'paper', NULL, '2026-08-24T23:59:00.000Z', 250, 'gcat_psych_major', NULL, 600, 600, 'high', 'divisible', 'anywhere', 'not_started', 'confirmed', 0),
  ('wi_psych_sources', 'crs_psych', 'wi_psych_paper', 'Find three psychology sources', NULL, 'milestone', NULL, '2026-08-02T23:59:00.000Z', NULL, NULL, NULL, 90, 90, 'high', 'divisible', 'library', 'not_started', 'confirmed', 0),
  ('wi_psych_outline', 'crs_psych', 'wi_psych_paper', 'Outline the paper against the rubric', NULL, 'milestone', NULL, '2026-08-09T23:59:00.000Z', NULL, NULL, NULL, 90, 90, 'high', 'divisible', 'anywhere', 'not_started', 'confirmed', 0),
  ('wi_psych_draft', 'crs_psych', 'wi_psych_paper', 'Write the full draft', NULL, 'milestone', NULL, '2026-08-18T23:59:00.000Z', NULL, NULL, NULL, 240, 240, 'high', 'divisible', 'anywhere', 'not_started', 'confirmed', 0),
  ('wi_psych_revise', 'crs_psych', 'wi_psych_paper', 'Revise against the rubric and proofread', NULL, 'milestone', NULL, '2026-08-23T23:59:00.000Z', NULL, NULL, NULL, 120, 120, 'medium', 'divisible', 'anywhere', 'not_started', 'confirmed', 0),
  ('wi_psych_reading_w2', 'crs_psych', NULL, 'Read chapter 4: Cognitive development', NULL, 'reading', NULL, '2026-07-29T10:00:00.000Z', 10, 'gcat_psych_reading', NULL, 60, 60, 'low', 'divisible', 'anywhere', 'not_started', 'confirmed', 0),
  ('wi_psych_quiz_w2', 'crs_psych', NULL, 'Quiz 2: Chapters 3-4', NULL, 'quiz_prep', NULL, '2026-07-31T10:00:00.000Z', 25, 'gcat_psych_quiz', NULL, 45, 45, 'medium', 'divisible', 'anywhere', 'not_started', 'confirmed', 0),
  ('wi_edu_project', 'crs_edu', NULL, 'Childhood Education Field Project', 'Observation log, analysis, and presentation.', 'group_project', NULL, '2026-09-07T23:59:00.000Z', 200, 'gcat_edu_major', NULL, 720, 720, 'high', 'divisible', 'anywhere', 'not_started', 'confirmed', 0),
  ('wi_edu_site', 'crs_edu', 'wi_edu_project', 'Confirm observation site and permissions', NULL, 'milestone', NULL, '2026-08-07T23:59:00.000Z', NULL, NULL, NULL, 60, 60, 'medium', 'divisible', 'anywhere', 'not_started', 'confirmed', 0),
  ('wi_edu_observe', 'crs_edu', 'wi_edu_project', 'Complete first observation session', NULL, 'milestone', NULL, '2026-08-16T23:59:00.000Z', NULL, NULL, NULL, 120, 120, 'medium', 'divisible', 'campus', 'not_started', 'confirmed', 0),
  ('wi_edu_reading_w2', 'crs_edu', NULL, 'Read: Play-based learning models', NULL, 'reading', NULL, '2026-07-30T09:00:00.000Z', 15, 'gcat_edu_reading', NULL, 50, 50, 'low', 'divisible', 'anywhere', 'not_started', 'confirmed', 0),
  ('wi_edu_quiz_w2', 'crs_edu', NULL, 'Quiz 2: Foundations', NULL, 'quiz_prep', NULL, '2026-08-04T09:00:00.000Z', 20, 'gcat_edu_quiz', NULL, 40, 40, 'medium', 'divisible', 'anywhere', 'not_started', 'confirmed', 0);

INSERT INTO dependencies (id, predecessor_work_item_id, successor_work_item_id, dependency_type) VALUES
  ('dep_sources_outline', 'wi_psych_sources', 'wi_psych_outline', 'finish_to_start'),
  ('dep_outline_draft', 'wi_psych_outline', 'wi_psych_draft', 'finish_to_start'),
  ('dep_draft_revise', 'wi_psych_draft', 'wi_psych_revise', 'finish_to_start'),
  ('dep_site_observe', 'wi_edu_site', 'wi_edu_observe', 'finish_to_start');

INSERT INTO grade_results (id, work_item_id, points_earned, points_possible, letter_grade, posted_at, confirmation_status, source_document_id, dropped) VALUES
  ('grd_psych_quiz1', 'wi_psych_quiz_w2', 17, 25, NULL, '2026-07-24T18:00:00.000Z', 'confirmed', NULL, 0),
  ('grd_psych_reading1', 'wi_psych_reading_w2', NULL, 10, NULL, NULL, 'confirmed', NULL, 0),
  ('grd_edu_quiz1', 'wi_edu_quiz_w2', 19, 20, NULL, '2026-07-24T18:00:00.000Z', 'confirmed', NULL, 0);
